"""Transactional email via Resend for audit confirmations."""

from __future__ import annotations

import logging

import resend

from app.config import settings
from app.schemas import AuditResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML email builder
# ---------------------------------------------------------------------------


def _build_audit_email_html(public_id: str, audit_result: AuditResult) -> str:
    """Construct a concise HTML email body summarising the audit."""
    score = audit_result.overspend_score
    efficiency_score = 100 - score
    monthly = audit_result.total_estimated_monthly_savings
    annual = audit_result.total_estimated_annual_savings
    tools = ", ".join(audit_result.tools_analyzed)
    audit_url = f"{settings.frontend_url}/audit/{public_id}"

    # Dynamic CTA block based on potential savings
    if monthly >= 500:
        cta = (
            "<p style='font-size:15px;line-height:1.6;'>With potential savings of <strong style='color:#0052FF;'>${monthly:,.2f}/month</strong>, "
            "you may benefit from a personalised consultation to help capture "
            "these savings quickly.</p>"
            '<p style="margin-top:24px;"><a href="https://credex.co/consult" '
            'style="background:#0052FF;color:#fff;padding:12px 24px;'
            'text-decoration:none;border-radius:4px;font-weight:bold;font-size:14px;">Book a Free Consultation</a></p>'
        ).format(monthly=monthly)
    elif monthly < 100:
        cta = (
            "<p style='font-size:15px;line-height:1.6;color:#64748b;'>Your infrastructure looks well-optimised! We'll let you know if we "
            "spot new liquidity opportunities in the future.</p>"
        )
    else:
        cta = (
            "<p style='font-size:15px;line-height:1.6;color:#64748b;'>There are some optimisation opportunities worth exploring. "
            "Review the full breakdown in your secure report.</p>"
        )

    return f"""\
<div style="font-family:Inter,system-ui,sans-serif;max-width:600px;margin:0 auto;background:#FAFAF9;padding:40px;border:1px solid #E2E8F0;border-radius:4px;">
  <div style="border-bottom:1px solid #0052FF;padding-bottom:16px;margin-bottom:32px;">
    <h2 style="color:#0052FF;margin:0;font-size:24px;letter-spacing:-0.02em;">Spend Node <span style="font-size:11px;text-transform:uppercase;color:#64748b;letter-spacing:0.05em;vertical-align:middle;margin-left:8px;">by Credex</span></h2>
    <p style="margin:8px 0 0 0;font-size:12px;color:#64748b;font-family:monospace;text-transform:uppercase;letter-spacing:0.05em;">Liquidity Analysis Complete</p>
  </div>

  <table style="width:100%;border-collapse:collapse;margin:0 0 32px 0;background:#FFFFFF;border:1px solid #E2E8F0;border-radius:4px;overflow:hidden;">
    <tr style="border-bottom:1px solid #E2E8F0;">
      <td style="padding:16px;font-size:13px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Efficiency Score</td>
      <td style="padding:16px;text-align:right;font-family:monospace;font-weight:bold;color:#0052FF;font-size:18px;">{efficiency_score}/100</td>
    </tr>
    <tr style="border-bottom:1px solid #E2E8F0;">
      <td style="padding:16px;font-size:13px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Monthly Spend</td>
      <td style="padding:16px;text-align:right;font-family:monospace;font-weight:bold;color:#1A1A1A;font-size:16px;">${audit_result.total_monthly_spend:,.2f}</td>
    </tr>
    <tr style="border-bottom:1px solid #E2E8F0;">
      <td style="padding:16px;font-size:13px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Annual Liquidity</td>
      <td style="padding:16px;text-align:right;font-family:monospace;font-weight:bold;color:#1A1A1A;font-size:16px;">${annual:,.2f}</td>
    </tr>
    <tr>
      <td style="padding:16px;font-size:13px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Nodes Analyzed</td>
      <td style="padding:16px;text-align:right;font-family:monospace;color:#1A1A1A;font-size:14px;">{tools}</td>
    </tr>
  </table>

  {cta}

  <p style="margin-top:32px;"><a href="{audit_url}" style="color:#0052FF;font-weight:600;text-decoration:none;border-bottom:1px solid #0052FF;padding-bottom:2px;">Access your full liquidity report →</a></p>

  <hr style="border:none;border-top:1px dashed #cbd5e1;margin:40px 0 24px 0;" />
  <p style="font-size:11px;color:#94a3b8;font-family:monospace;text-transform:uppercase;line-height:1.5;">
    Generated by Spend Node. You are receiving this secure link because you requested a cloud infrastructure analysis via Credex.
  </p>
</div>
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def send_audit_confirmation(
    email: str,
    public_id: str,
    audit_result: AuditResult,
) -> bool:
    """Send an HTML audit confirmation email.

    Returns ``True`` on success, ``False`` on failure. Never raises — all
    errors are caught and logged.
    """
    if not settings.resend_api_key:
        logger.warning("Resend API key not configured — skipping email to %s", email)
        return False

    resend.api_key = settings.resend_api_key

    html = _build_audit_email_html(public_id, audit_result)
    subject = f"Your AI Spend Audit — Score: {audit_result.overspend_score}/100"

    try:
        resend.Emails.send(
            {
                "from": settings.resend_from_email,
                "to": [email],
                "subject": subject,
                "html": html,
            }
        )
        logger.info("Audit email sent to %s for audit %s", email, public_id)
        return True
    except Exception:
        logger.exception("Failed to send audit email to %s", email)
        return False
